import type { Product, PreorderBrand, Order, Preorder } from "./types";

/**
 * Stand-in catalog. Shape mirrors the future Supabase `products` table
 * (see supabase/schema.sql once Phase 2 lands) so swapping this module
 * for real queries later is a drop-in change, not a rewrite.
 */
export const products: Product[] = [
  {
    id: "p1",
    slug: "silk-veil-blush",
    name: "Silk Veil Blush",
    category: "makeup",
    price: 28,
    cost: 9,
    art: "rose",
    stockQuantity: 42,
    lowStockThreshold: 10,
    bestseller: true,
    rating: 4.8,
    reviewCount: 214,
    variants: ["Petal", "Rosewood", "Terracotta", "Berry"],
    concerns: ["everyday-glam", "date-night"],
  },
  {
    id: "p2",
    slug: "dew-drop-serum",
    name: "Dew Drop Serum",
    category: "skincare",
    price: 46,
    cost: 17,
    art: "peach",
    stockQuantity: 8,
    lowStockThreshold: 10,
    rating: 4.7,
    reviewCount: 132,
    concerns: ["glowy-skin"],
  },
  {
    id: "p3",
    slug: "petite-top-handle",
    name: "Petite Top-Handle",
    category: "handbags",
    brand: "Coach",
    price: 118,
    cost: 52,
    art: "sand",
    stockQuantity: 5,
    lowStockThreshold: 6,
    rating: 4.9,
    reviewCount: 58,
    variants: ["Cream", "Blush", "Espresso"],
    concerns: ["everyday-glam", "office-ready"],
  },
  {
    id: "p4",
    slug: "velvet-matte-rouge",
    name: "Velvet Matte Rouge",
    category: "makeup",
    price: 24,
    cost: 8,
    art: "clay",
    stockQuantity: 3,
    lowStockThreshold: 10,
    rating: 4.6,
    reviewCount: 301,
    variants: ["Blush Nude", "Cherry", "Mauve", "Brick"],
    concerns: ["date-night", "everyday-glam"],
  },
  {
    id: "p5",
    slug: "barely-there-tint",
    name: "Barely-There Tint",
    category: "skincare",
    price: 22,
    cost: 7,
    art: "moss",
    stockQuantity: 30,
    lowStockThreshold: 10,
    rating: 4.5,
    reviewCount: 89,
    concerns: ["glowy-skin", "office-ready"],
  },
  {
    id: "p6",
    slug: "structured-tote",
    name: "Structured Tote",
    category: "handbags",
    brand: "Michael Kors",
    price: 168,
    cost: 74,
    art: "clay",
    imageUrl: "/images/products/structured-tote.avif",
    stockQuantity: 12,
    lowStockThreshold: 6,
    rating: 4.8,
    reviewCount: 41,
    variants: ["Oat", "Moss", "Black"],
    concerns: ["office-ready"],
  },
  // --- Real photos below (Phase 4 test batch) ---
  {
    id: "p7",
    slug: "denim-satchel",
    name: "Denim Satchel",
    category: "handbags",
    brand: "Michael Kors",
    price: 148,
    cost: 65,
    art: "sand",
    imageUrl: "/images/products/denim-satchel.avif",
    stockQuantity: 9,
    lowStockThreshold: 6,
    rating: 4.7,
    reviewCount: 22,
    concerns: ["everyday-glam"],
  },
  {
    id: "p8",
    slug: "signature-weekender",
    name: "Signature Weekender",
    category: "handbags",
    brand: "Michael Kors",
    price: 228,
    cost: 98,
    art: "clay",
    imageUrl: "/images/products/signature-weekender.avif",
    stockQuantity: 6,
    lowStockThreshold: 5,
    rating: 4.8,
    reviewCount: 15,
    concerns: ["office-ready"],
  },
  {
    id: "p9",
    slug: "pebbled-leather-tote",
    name: "Pebbled Leather Tote",
    category: "handbags",
    brand: "Michael Kors",
    price: 198,
    cost: 86,
    art: "clay",
    imageUrl: "/images/products/pebbled-leather-tote.avif",
    stockQuantity: 10,
    lowStockThreshold: 6,
    rating: 4.9,
    reviewCount: 33,
    concerns: ["office-ready", "everyday-glam"],
  },
  {
    id: "p10",
    slug: "vanilla-monogram-tote",
    name: "Vanilla Monogram Tote",
    category: "handbags",
    brand: "Michael Kors",
    price: 188,
    cost: 82,
    art: "sand",
    imageUrl: "/images/products/vanilla-monogram-tote.avif",
    stockQuantity: 14,
    lowStockThreshold: 6,
    rating: 4.7,
    reviewCount: 27,
    concerns: ["everyday-glam"],
  },
  {
    id: "p11",
    slug: "blush-monogram-tote",
    name: "Blush Monogram Tote",
    category: "handbags",
    brand: "Michael Kors",
    price: 178,
    cost: 78,
    art: "rose",
    imageUrl: "/images/products/blush-monogram-tote.avif",
    stockQuantity: 11,
    lowStockThreshold: 6,
    rating: 4.8,
    reviewCount: 19,
    concerns: ["everyday-glam", "date-night"],
  },
  {
    id: "p12",
    slug: "navy-monogram-tote",
    name: "Navy Monogram Tote & Pouch",
    category: "handbags",
    brand: "Michael Kors",
    price: 208,
    cost: 90,
    art: "clay",
    imageUrl: "/images/products/navy-monogram-tote.avif",
    stockQuantity: 8,
    lowStockThreshold: 6,
    rating: 4.9,
    reviewCount: 24,
    concerns: ["office-ready"],
  },
  {
    id: "p13",
    slug: "zero-pore-toner-pads",
    name: "Zero Pore Toner Pads",
    category: "skincare",
    brand: "Medicube",
    price: 28,
    cost: 10,
    art: "moss",
    imageUrl: "/images/products/zero-pore-toner-pads.jpg",
    stockQuantity: 40,
    lowStockThreshold: 12,
    rating: 4.6,
    reviewCount: 512,
    concerns: ["glowy-skin"],
  },
  {
    id: "p14",
    slug: "triple-lipid-restore",
    name: "Triple Lipid Restore 2:4:2",
    category: "skincare",
    brand: "SkinCeuticals",
    price: 98,
    cost: 42,
    art: "peach",
    imageUrl: "/images/products/triple-lipid-restore.webp",
    stockQuantity: 10,
    lowStockThreshold: 6,
    rating: 4.8,
    reviewCount: 96,
    concerns: ["glowy-skin"],
  },
  {
    id: "p15",
    slug: "advanced-rgn-serum",
    name: "Advanced RGN Serum",
    category: "skincare",
    brand: "SkinCeuticals",
    price: 195,
    cost: 85,
    art: "clay",
    imageUrl: "/images/products/advanced-rgn-serum.webp",
    stockQuantity: 6,
    lowStockThreshold: 4,
    rating: 4.9,
    reviewCount: 58,
    concerns: ["glowy-skin"],
  },
  {
    id: "p16",
    slug: "night-repair-therapy",
    name: "Night Repair Therapy",
    category: "skincare",
    brand: "The Skin Diary",
    price: 54,
    cost: 21,
    art: "sand",
    imageUrl: "/images/products/night-repair-therapy.webp",
    stockQuantity: 18,
    lowStockThreshold: 8,
    rating: 4.7,
    reviewCount: 74,
    concerns: ["glowy-skin"],
  },
  {
    id: "p17",
    slug: "p-tiox-peptide-duo",
    name: "P-TIOX Peptide Duo",
    category: "skincare",
    brand: "SkinCeuticals",
    price: 158,
    cost: 68,
    art: "moss",
    imageUrl: "/images/products/p-tiox-peptide-duo.webp",
    stockQuantity: 7,
    lowStockThreshold: 5,
    rating: 4.8,
    reviewCount: 41,
    concerns: ["glowy-skin"],
  },
  {
    id: "p18",
    slug: "lip-sleeping-mask",
    name: "Lip Sleeping Mask, Berry",
    category: "skincare",
    brand: "Laneige",
    price: 26,
    cost: 9,
    art: "rose",
    imageUrl: "/images/products/lip-sleeping-mask.jpg",
    stockQuantity: 35,
    lowStockThreshold: 12,
    rating: 4.8,
    reviewCount: 803,
    concerns: ["glowy-skin", "date-night"],
  },
  {
    id: "p19",
    slug: "heartleaf-soothing-toner",
    name: "Heartleaf 77% Soothing Toner",
    category: "skincare",
    brand: "Anua",
    price: 25,
    cost: 8,
    art: "peach",
    imageUrl: "/images/products/heartleaf-soothing-toner.jpg",
    stockQuantity: 28,
    lowStockThreshold: 10,
    rating: 4.7,
    reviewCount: 266,
    concerns: ["glowy-skin"],
  },
  {
    id: "p20",
    slug: "glow-deep-rice-milk",
    name: "Glow Deep Rice Milk",
    category: "skincare",
    brand: "Beauty of Joseon",
    price: 19,
    cost: 6,
    art: "sand",
    imageUrl: "/images/products/glow-deep-rice-milk.jpg",
    stockQuantity: 33,
    lowStockThreshold: 10,
    rating: 4.6,
    reviewCount: 189,
    concerns: ["glowy-skin"],
  },
  {
    id: "p21",
    slug: "complexion-trio",
    name: "Award-Winning Complexion Trio",
    category: "makeup",
    brand: "Charlotte Tilbury",
    price: 89,
    cost: 36,
    art: "clay",
    imageUrl: "/images/products/complexion-trio.webp",
    stockQuantity: 9,
    lowStockThreshold: 6,
    rating: 4.9,
    reviewCount: 47,
    concerns: ["everyday-glam"],
  },
  {
    id: "p22",
    slug: "pillow-lip-trio",
    name: "Pillow Lip Trio",
    category: "makeup",
    brand: "Charlotte Tilbury",
    price: 75,
    cost: 30,
    art: "rose",
    imageUrl: "/images/products/pillow-lip-trio.webp",
    stockQuantity: 12,
    lowStockThreshold: 6,
    rating: 4.8,
    reviewCount: 63,
    concerns: ["date-night"],
  },
  {
    id: "p23",
    slug: "glow-stick-trio",
    name: "Hollywood Glow Stick Trio",
    category: "makeup",
    brand: "Charlotte Tilbury",
    price: 99,
    cost: 40,
    art: "peach",
    imageUrl: "/images/products/glow-stick-trio.webp",
    stockQuantity: 8,
    lowStockThreshold: 6,
    rating: 4.9,
    reviewCount: 38,
    concerns: ["everyday-glam"],
  },
  {
    id: "p24",
    slug: "minis-kit",
    name: "Unreal Minis Kit",
    category: "makeup",
    brand: "Charlotte Tilbury",
    price: 65,
    cost: 26,
    art: "rose",
    imageUrl: "/images/products/minis-kit.webp",
    stockQuantity: 14,
    lowStockThreshold: 6,
    rating: 4.7,
    reviewCount: 29,
    concerns: ["everyday-glam", "bridal"],
  },
  {
    id: "p25",
    slug: "airbrush-foundation-stick",
    name: "Airbrush Foundation Stick",
    category: "makeup",
    brand: "Charlotte Tilbury",
    price: 44,
    cost: 18,
    art: "sand",
    imageUrl: "/images/products/airbrush-foundation-stick.webp",
    stockQuantity: 20,
    lowStockThreshold: 8,
    rating: 4.8,
    reviewCount: 112,
    variants: ["Fair", "Light", "Medium", "Tan"],
    concerns: ["everyday-glam", "office-ready"],
  },
  {
    id: "p26",
    slug: "beach-glow-duo",
    name: "Beach Glow Duo",
    category: "makeup",
    brand: "Charlotte Tilbury",
    price: 58,
    cost: 23,
    art: "peach",
    imageUrl: "/images/products/beach-glow-duo.webp",
    stockQuantity: 10,
    lowStockThreshold: 6,
    rating: 4.8,
    reviewCount: 21,
    concerns: ["everyday-glam", "date-night"],
  },
];

export const preorderBrands: PreorderBrand[] = [
  { name: "Louis Vuitton", art: "clay" },
  { name: "Chanel", art: "rose" },
  { name: "Dior", art: "sand" },
];

export const shopByLook = [
  { slug: "glowy-skin", label: "Glowy Skin" },
  { slug: "everyday-glam", label: "Everyday Glam" },
  { slug: "date-night", label: "Date Night" },
  { slug: "office-ready", label: "Office Ready" },
  { slug: "bridal", label: "Bridal" },
];

export const orders: Order[] = [
  {
    id: "ord_1042",
    customerName: "Layla Haddad",
    customerEmail: "layla.h@example.com",
    items: "Silk Veil Blush (Rosewood), Dew Drop Serum",
    total: 74,
    placedAt: "2026-07-26T09:14:00Z",
    status: "new",
  },
  {
    id: "ord_1041",
    customerName: "Ranya Kassem",
    customerEmail: "ranya.k@example.com",
    items: "Petite Top-Handle (Blush)",
    total: 118,
    placedAt: "2026-07-25T21:02:00Z",
    status: "new",
  },
  {
    id: "ord_1040",
    customerName: "Dina Farouk",
    customerEmail: "dina.f@example.com",
    items: "Velvet Matte Rouge (Cherry) x2",
    total: 48,
    placedAt: "2026-07-25T16:47:00Z",
    status: "fulfilled",
  },
];

export const preorders: Preorder[] = [
  {
    id: "pre_1",
    customerName: "Yasmin Odeh",
    customerEmail: "yasmin.o@example.com",
    brand: "Chanel",
    styleReference: "Classic Flap, medium, caviar black/gold",
    itemPrice: 8800,
    depositAmount: 4400,
    status: "deposit_paid",
    createdAt: "2026-07-20T10:00:00Z",
  },
  {
    id: "pre_2",
    customerName: "Farah Nasser",
    customerEmail: "farah.n@example.com",
    brand: "Louis Vuitton",
    styleReference: "Neverfull MM, Damier Ebene",
    itemPrice: 1740,
    depositAmount: 870,
    status: "arrived",
    createdAt: "2026-07-12T14:30:00Z",
  },
];

// Computed helpers (bestsellers, lowStock, profitByCategory) live in
// `src/lib/product-utils.ts` — they're pure functions over `Product[]` so
// the same logic works whether the array came from here or from Supabase.
